# Use the official Node.js image as the base
FROM node:16 as build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json (for caching dependencies)
COPY package*.json ./
COPY package.json /app/
COPY package-lock.json /app/

# Install the dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Build the React app for production
RUN npm run build

# Serve the React app using a lightweight web server (e.g., nginx)
FROM nginx:alpine

# Copy the build folder from the previous image to nginx's serving folder
COPY --from=build /app/build /usr/share/nginx/html

# Replace default Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose the port nginx will listen on -- for cloud run 
EXPOSE 8080

# Start nginx when the container runs
CMD ["nginx", "-g", "daemon off;"]